input: samples_mouse.csv
outdir: ./results
email: asa.bjorklund@scililfelab.se
preprocess_only: false
ambient_removal: cellbender
doublet_detection: scrublet,scds,solo
doublet_detection_threshold: 2
integration_methods: scanvi,harmony
integration_hvgs: 4000
skip_liana: true 