name: scanpy_scQC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.10
  - pip
  - matplotlib-base
  - matplotlib-inline
  - numpydoc
  - seaborn=0.13.2
  - seaborn-base
  - urllib3
  - ipykernel
  - compilers
  - quarto
  - notebook
  - geopandas
  - harmonypy
  - leidenalg
  - matplotlib-scalebar
  - matplotlib-venn
  - numpy=1.26.4
  - pandas=1.5.3
  - scipy=1.14.1
  - pybiomart
  - scanpy=1.10.3
  - anndata=0.10.8
  - scikit-learn=1.1.3
  - scikit-misc
  - scrublet
  - celltypist
  - scarches
  - scvi-tools=1.2.0
  - scanorama=1.7.4
  - gseapy
  - fa2
  - plotly
  - python-kaleido # static image export
  
#  - mathjax # testing if needed for plotly 
#  - cellrank=2.0.6 # testing, possibly remove if not used.
#  - pyhamcrest # for rpy2
#  - readline
#  - anndata2ri
#  - pip:
#    - fa2-modified  # obs, paga now needs fa2-modified package, not available as conda, need to install with pip.
#    - rpy2

#  - nb_conda_kernels  # skip, gives problem with neighbors
#  - jupyter_contrib_nbextensions  # skip, gives problem with neighbors
#  - traitlets<=5.9.0  # testing downgrade to see if it fixes issue with pp.neighbors crashing.


# Encountered problems while solving:
#  - package bbknn-1.6.0-py310he07d9a1_0 requires numpy >=1.26.2,<2.0a0, but none of the providers can be installed
#  - package scarches-0.6.1-pyh7e72e81_0 requires schpl >=1.0.0, but none of the providers can be installed
